# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/proc_system.bd
# Block Designs: The module: 'proc_system' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_processing_system7_0_0/proc_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_processing_system7_0_0 || ORIG_REF_NAME==proc_system_processing_system7_0_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_axi_gpio_0_0 || ORIG_REF_NAME==proc_system_axi_gpio_0_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_1_0/proc_system_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_axi_gpio_1_0 || ORIG_REF_NAME==proc_system_axi_gpio_1_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_xbar_0/proc_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_xbar_0 || ORIG_REF_NAME==proc_system_xbar_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_ps7_0_axi_periph_0/proc_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==proc_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_rst_ps7_0_100M_0/proc_system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==proc_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_auto_pc_0/proc_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_auto_pc_0 || ORIG_REF_NAME==proc_system_auto_pc_0} -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_processing_system7_0_0/proc_system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==proc_system_processing_system7_0_0 || ORIG_REF_NAME==proc_system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==proc_system_axi_gpio_0_0 || ORIG_REF_NAME==proc_system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0_ooc.xdc

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==proc_system_axi_gpio_0_0 || ORIG_REF_NAME==proc_system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_1_0/proc_system_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==proc_system_axi_gpio_1_0 || ORIG_REF_NAME==proc_system_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_1_0/proc_system_axi_gpio_1_0_ooc.xdc

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_1_0/proc_system_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==proc_system_axi_gpio_1_0 || ORIG_REF_NAME==proc_system_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_rst_ps7_0_100M_0/proc_system_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==proc_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==proc_system_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_rst_ps7_0_100M_0/proc_system_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==proc_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==proc_system_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_auto_pc_0/proc_system_auto_pc_0_ooc.xdc

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/proc_system_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system'. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/proc_system.bd
# Block Designs: The module: 'proc_system' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_processing_system7_0_0/proc_system_processing_system7_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_processing_system7_0_0 || ORIG_REF_NAME==proc_system_processing_system7_0_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_axi_gpio_0_0 || ORIG_REF_NAME==proc_system_axi_gpio_0_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_1_0/proc_system_axi_gpio_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_axi_gpio_1_0 || ORIG_REF_NAME==proc_system_axi_gpio_1_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_xbar_0/proc_system_xbar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_xbar_0 || ORIG_REF_NAME==proc_system_xbar_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_ps7_0_axi_periph_0/proc_system_ps7_0_axi_periph_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==proc_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_rst_ps7_0_100M_0/proc_system_rst_ps7_0_100M_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==proc_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_auto_pc_0/proc_system_auto_pc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_system_auto_pc_0 || ORIG_REF_NAME==proc_system_auto_pc_0} -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_processing_system7_0_0/proc_system_processing_system7_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==proc_system_processing_system7_0_0 || ORIG_REF_NAME==proc_system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==proc_system_axi_gpio_0_0 || ORIG_REF_NAME==proc_system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0_ooc.xdc

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==proc_system_axi_gpio_0_0 || ORIG_REF_NAME==proc_system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_1_0/proc_system_axi_gpio_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==proc_system_axi_gpio_1_0 || ORIG_REF_NAME==proc_system_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_1_0/proc_system_axi_gpio_1_0_ooc.xdc

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_1_0/proc_system_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==proc_system_axi_gpio_1_0 || ORIG_REF_NAME==proc_system_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_rst_ps7_0_100M_0/proc_system_rst_ps7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==proc_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==proc_system_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_rst_ps7_0_100M_0/proc_system_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==proc_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==proc_system_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_auto_pc_0/proc_system_auto_pc_0_ooc.xdc

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/proc_system_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system'. Do not add the DONT_TOUCH constraint.
