# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param project.vivado.isBlockSynthRun true
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/vivado/vivado.cache/wt [current_project]
set_property parent.project_path /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/vivado/vivado.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
set_property ip_output_repo /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/vivado/vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/proc_system.bd
set_property used_in_implementation false [get_files -all /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_processing_system7_0_0/proc_system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_1_0/proc_system_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_1_0/proc_system_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_axi_gpio_1_0/proc_system_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_rst_ps7_0_100M_0/proc_system_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_rst_ps7_0_100M_0/proc_system_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/ip/proc_system_auto_pc_0/proc_system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/proc_system_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top proc_system -part xc7z020clg484-1 -mode out_of_context

rename_ref -prefix_all proc_system_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef proc_system.dcp
create_report "proc_system_synth_1_synth_report_utilization_0" "report_utilization -file proc_system_utilization_synth.rpt -pb proc_system_utilization_synth.pb"

if { [catch {
  file copy -force /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/vivado/vivado.runs/proc_system_synth_1/proc_system.dcp /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/proc_system.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/proc_system_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/proc_system_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/proc_system_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/proc_system_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/vivado/vivado.ip_user_files/bd/proc_system]} {
  catch { 
    file copy -force /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/proc_system_stub.v /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/vivado/vivado.ip_user_files/bd/proc_system
  }
}

if {[file isdir /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/vivado/vivado.ip_user_files/bd/proc_system]} {
  catch { 
    file copy -force /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/src/ip/proc_system/proc_system_stub.vhdl /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_systems/rtl/vivado/vivado.ip_user_files/bd/proc_system
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
