
####################################################################################
# Generated by Vivado 2018.3 built on 'Thu Dec  6 23:36:41 MST 2018' by 'xbuild'
# Command Used: write_xdc -force /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/constr/constrs_1.xdc
####################################################################################


####################################################################################
# Constraints from file : 'ps_system_processing_system7_0_0.xdc'
####################################################################################

############################################################################
##
##  Xilinx, Inc. 2006            www.xilinx.com
############################################################################
##  File name :       ps7_constraints.xdc
##
##  Details :     Constraints file
##                    FPGA family:       zynq
##                    FPGA:              xc7z020clg484-1
##                    Device Size:        xc7z020
##                    Package:            clg484
##                    Speedgrade:         -1
##
##
############################################################################
############################################################################
############################################################################
# Clock constraints                                                        #
############################################################################
current_instance proc_system_0/ps_system_i/processing_system7_0/inst
create_clock -period 10.000 -name clk_fpga_0 [get_pins {PS7_i/FCLKCLK[0]}]
set_input_jitter clk_fpga_0 0.300
#The clocks are asynchronous, user should constrain them appropriately.#


############################################################################
# I/O STANDARDS and Location Constraints                                   #
############################################################################

#  Enet 0 / mdio / MIO[53]
current_instance -quiet
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[53]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[53]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[53]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[53]}]
#  Enet 0 / mdc / MIO[52]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[52]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[52]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[52]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[52]}]
#  GPIO / gpio[51] / MIO[51]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[51]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[51]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[51]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[51]}]
#  GPIO / gpio[50] / MIO[50]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[50]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[50]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[50]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[50]}]
#  UART 1 / rx / MIO[49]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[49]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[49]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[49]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[49]}]
#  UART 1 / tx / MIO[48]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[48]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[48]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[48]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[48]}]
#  SD 0 / cd / MIO[47]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[47]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[47]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[47]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[47]}]
#  SD 0 / wp / MIO[46]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[46]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[46]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[46]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[46]}]
#  SD 0 / data[3] / MIO[45]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[45]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[45]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[45]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[45]}]
#  SD 0 / data[2] / MIO[44]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[44]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[44]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[44]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[44]}]
#  SD 0 / data[1] / MIO[43]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[43]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[43]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[43]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[43]}]
#  SD 0 / data[0] / MIO[42]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[42]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[42]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[42]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[42]}]
#  SD 0 / cmd / MIO[41]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[41]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[41]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[41]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[41]}]
#  SD 0 / clk / MIO[40]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[40]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[40]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[40]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[40]}]
#  USB 0 / data[7] / MIO[39]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[39]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[39]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[39]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[39]}]
#  USB 0 / data[6] / MIO[38]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[38]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[38]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[38]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[38]}]
#  USB 0 / data[5] / MIO[37]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[37]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[37]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[37]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[37]}]
#  USB 0 / clk / MIO[36]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[36]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[36]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[36]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[36]}]
#  USB 0 / data[3] / MIO[35]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[35]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[35]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[35]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[35]}]
#  USB 0 / data[2] / MIO[34]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[34]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[34]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[34]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[34]}]
#  USB 0 / data[1] / MIO[33]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[33]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[33]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[33]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[33]}]
#  USB 0 / data[0] / MIO[32]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[32]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[32]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[32]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[32]}]
#  USB 0 / nxt / MIO[31]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[31]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[31]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[31]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[31]}]
#  USB 0 / stp / MIO[30]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[30]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[30]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[30]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[30]}]
#  USB 0 / dir / MIO[29]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[29]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[29]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[29]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[29]}]
#  USB 0 / data[4] / MIO[28]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[28]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[28]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[28]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[28]}]
#  Enet 0 / rx_ctl / MIO[27]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[27]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[27]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[27]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[27]}]
#  Enet 0 / rxd[3] / MIO[26]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[26]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[26]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[26]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[26]}]
#  Enet 0 / rxd[2] / MIO[25]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[25]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[25]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[25]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[25]}]
#  Enet 0 / rxd[1] / MIO[24]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[24]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[24]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[24]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[24]}]
#  Enet 0 / rxd[0] / MIO[23]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[23]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[23]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[23]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[23]}]
#  Enet 0 / rx_clk / MIO[22]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[22]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[22]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[22]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[22]}]
#  Enet 0 / tx_ctl / MIO[21]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[21]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[21]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[21]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[21]}]
#  Enet 0 / txd[3] / MIO[20]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[20]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[20]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[20]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[20]}]
#  Enet 0 / txd[2] / MIO[19]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[19]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[19]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[19]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[19]}]
#  Enet 0 / txd[1] / MIO[18]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[18]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[18]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[18]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[18]}]
#  Enet 0 / txd[0] / MIO[17]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[17]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[17]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[17]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[17]}]
#  Enet 0 / tx_clk / MIO[16]
set_property IOSTANDARD LVCMOS18 [get_ports {FIXED_IO_mio[16]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[16]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[16]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[16]}]
#  GPIO / gpio[15] / MIO[15]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[15]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[15]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[15]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[15]}]
#  GPIO / gpio[14] / MIO[14]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[14]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[14]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[14]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[14]}]
#  GPIO / gpio[13] / MIO[13]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[13]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[13]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[13]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[13]}]
#  GPIO / gpio[12] / MIO[12]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[12]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[12]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[12]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[12]}]
#  GPIO / gpio[11] / MIO[11]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[11]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[11]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[11]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[11]}]
#  GPIO / gpio[10] / MIO[10]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[10]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[10]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[10]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[10]}]
#  GPIO / gpio[9] / MIO[9]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[9]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[9]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[9]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[9]}]
#  GPIO / gpio[8] / MIO[8]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[8]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[8]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[8]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[8]}]
#  GPIO / gpio[7] / MIO[7]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[7]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[7]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[7]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[7]}]
#  Quad SPI Flash / qspi0_sclk / MIO[6]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[6]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[6]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[6]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[6]}]
#  Quad SPI Flash / qspi0_io[3]/HOLD_B / MIO[5]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[5]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[5]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[5]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[5]}]
#  Quad SPI Flash / qspi0_io[2] / MIO[4]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[4]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[4]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[4]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[4]}]
#  Quad SPI Flash / qspi0_io[1] / MIO[3]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[3]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[3]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[3]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[3]}]
#  Quad SPI Flash / qspi0_io[0] / MIO[2]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[2]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[2]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[2]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[2]}]
#  Quad SPI Flash / qspi0_ss_b / MIO[1]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[1]}]
set_property SLEW FAST [get_ports {FIXED_IO_mio[1]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[1]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[1]}]
#  GPIO / gpio[0] / MIO[0]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[0]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[0]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[0]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports FIXED_IO_ddr_vrp]
set_property SLEW FAST [get_ports FIXED_IO_ddr_vrp]
set_property PIO_DIRECTION BIDIR [get_ports FIXED_IO_ddr_vrp]
set_property IOSTANDARD SSTL15_T_DCI [get_ports FIXED_IO_ddr_vrn]
set_property SLEW FAST [get_ports FIXED_IO_ddr_vrn]
set_property PIO_DIRECTION BIDIR [get_ports FIXED_IO_ddr_vrn]
set_property IOSTANDARD SSTL15 [get_ports DDR_we_n]
set_property SLEW SLOW [get_ports DDR_we_n]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_we_n]
set_property IOSTANDARD SSTL15 [get_ports DDR_ras_n]
set_property SLEW SLOW [get_ports DDR_ras_n]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_ras_n]
set_property IOSTANDARD SSTL15 [get_ports DDR_odt]
set_property SLEW SLOW [get_ports DDR_odt]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_odt]
set_property IOSTANDARD SSTL15 [get_ports DDR_reset_n]
set_property SLEW FAST [get_ports DDR_reset_n]
set_property PIO_DIRECTION BIDIR [get_ports DDR_reset_n]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[3]}]
set_property SLEW FAST [get_ports {DDR_dqs_p[3]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[3]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[2]}]
set_property SLEW FAST [get_ports {DDR_dqs_p[2]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[2]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[1]}]
set_property SLEW FAST [get_ports {DDR_dqs_p[1]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[1]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[0]}]
set_property SLEW FAST [get_ports {DDR_dqs_p[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[0]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[3]}]
set_property SLEW FAST [get_ports {DDR_dqs_n[3]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[3]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[2]}]
set_property SLEW FAST [get_ports {DDR_dqs_n[2]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[2]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[1]}]
set_property SLEW FAST [get_ports {DDR_dqs_n[1]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[1]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[0]}]
set_property SLEW FAST [get_ports {DDR_dqs_n[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[0]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[9]}]
set_property SLEW FAST [get_ports {DDR_dq[9]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[9]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[8]}]
set_property SLEW FAST [get_ports {DDR_dq[8]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[8]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[7]}]
set_property SLEW FAST [get_ports {DDR_dq[7]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[7]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[6]}]
set_property SLEW FAST [get_ports {DDR_dq[6]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[6]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[5]}]
set_property SLEW FAST [get_ports {DDR_dq[5]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[5]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[4]}]
set_property SLEW FAST [get_ports {DDR_dq[4]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[4]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[3]}]
set_property SLEW FAST [get_ports {DDR_dq[3]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[3]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[31]}]
set_property SLEW FAST [get_ports {DDR_dq[31]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[31]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[30]}]
set_property SLEW FAST [get_ports {DDR_dq[30]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[30]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[2]}]
set_property SLEW FAST [get_ports {DDR_dq[2]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[2]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[29]}]
set_property SLEW FAST [get_ports {DDR_dq[29]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[29]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[28]}]
set_property SLEW FAST [get_ports {DDR_dq[28]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[28]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[27]}]
set_property SLEW FAST [get_ports {DDR_dq[27]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[27]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[26]}]
set_property SLEW FAST [get_ports {DDR_dq[26]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[26]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[25]}]
set_property SLEW FAST [get_ports {DDR_dq[25]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[25]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[24]}]
set_property SLEW FAST [get_ports {DDR_dq[24]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[24]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[23]}]
set_property SLEW FAST [get_ports {DDR_dq[23]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[23]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[22]}]
set_property SLEW FAST [get_ports {DDR_dq[22]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[22]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[21]}]
set_property SLEW FAST [get_ports {DDR_dq[21]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[21]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[20]}]
set_property SLEW FAST [get_ports {DDR_dq[20]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[20]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[1]}]
set_property SLEW FAST [get_ports {DDR_dq[1]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[1]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[19]}]
set_property SLEW FAST [get_ports {DDR_dq[19]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[19]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[18]}]
set_property SLEW FAST [get_ports {DDR_dq[18]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[18]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[17]}]
set_property SLEW FAST [get_ports {DDR_dq[17]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[17]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[16]}]
set_property SLEW FAST [get_ports {DDR_dq[16]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[16]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[15]}]
set_property SLEW FAST [get_ports {DDR_dq[15]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[15]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[14]}]
set_property SLEW FAST [get_ports {DDR_dq[14]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[14]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[13]}]
set_property SLEW FAST [get_ports {DDR_dq[13]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[13]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[12]}]
set_property SLEW FAST [get_ports {DDR_dq[12]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[12]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[11]}]
set_property SLEW FAST [get_ports {DDR_dq[11]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[11]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[10]}]
set_property SLEW FAST [get_ports {DDR_dq[10]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[10]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[0]}]
set_property SLEW FAST [get_ports {DDR_dq[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[0]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[3]}]
set_property SLEW FAST [get_ports {DDR_dm[3]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[3]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[2]}]
set_property SLEW FAST [get_ports {DDR_dm[2]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[2]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[1]}]
set_property SLEW FAST [get_ports {DDR_dm[1]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[1]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[0]}]
set_property SLEW FAST [get_ports {DDR_dm[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[0]}]
set_property IOSTANDARD SSTL15 [get_ports DDR_cs_n]
set_property SLEW SLOW [get_ports DDR_cs_n]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cs_n]
set_property IOSTANDARD SSTL15 [get_ports DDR_cke]
set_property SLEW SLOW [get_ports DDR_cke]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cke]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR_ck_p]
set_property SLEW FAST [get_ports DDR_ck_p]
set_property PIO_DIRECTION INPUT [get_ports DDR_ck_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR_ck_n]
set_property SLEW FAST [get_ports DDR_ck_n]
set_property PIO_DIRECTION INPUT [get_ports DDR_ck_n]
set_property IOSTANDARD SSTL15 [get_ports DDR_cas_n]
set_property SLEW SLOW [get_ports DDR_cas_n]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cas_n]
set_property IOSTANDARD SSTL15 [get_ports {DDR_ba[2]}]
set_property SLEW SLOW [get_ports {DDR_ba[2]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[2]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_ba[1]}]
set_property SLEW SLOW [get_ports {DDR_ba[1]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[1]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_ba[0]}]
set_property SLEW SLOW [get_ports {DDR_ba[0]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[0]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[9]}]
set_property SLEW SLOW [get_ports {DDR_addr[9]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[9]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[8]}]
set_property SLEW SLOW [get_ports {DDR_addr[8]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[8]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[7]}]
set_property SLEW SLOW [get_ports {DDR_addr[7]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[7]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[6]}]
set_property SLEW SLOW [get_ports {DDR_addr[6]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[6]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[5]}]
set_property SLEW SLOW [get_ports {DDR_addr[5]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[5]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[4]}]
set_property SLEW SLOW [get_ports {DDR_addr[4]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[4]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[3]}]
set_property SLEW SLOW [get_ports {DDR_addr[3]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[3]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[2]}]
set_property SLEW SLOW [get_ports {DDR_addr[2]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[2]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[1]}]
set_property SLEW SLOW [get_ports {DDR_addr[1]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[1]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[14]}]
set_property SLEW SLOW [get_ports {DDR_addr[14]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[14]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[13]}]
set_property SLEW SLOW [get_ports {DDR_addr[13]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[13]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[12]}]
set_property SLEW SLOW [get_ports {DDR_addr[12]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[12]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[11]}]
set_property SLEW SLOW [get_ports {DDR_addr[11]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[11]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[10]}]
set_property SLEW SLOW [get_ports {DDR_addr[10]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[10]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[0]}]
set_property SLEW SLOW [get_ports {DDR_addr[0]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_porb]
set_property SLEW FAST [get_ports FIXED_IO_ps_porb]
set_property IOSTANDARD LVCMOS18 [get_ports FIXED_IO_ps_srstb]
set_property SLEW FAST [get_ports FIXED_IO_ps_srstb]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_clk]
set_property PACKAGE_PIN C9 [get_ports FIXED_IO_ps_srstb]
set_property PACKAGE_PIN R5 [get_ports DDR_ras_n]
set_property PACKAGE_PIN B5 [get_ports FIXED_IO_ps_porb]
set_property PACKAGE_PIN P5 [get_ports DDR_odt]
set_property PACKAGE_PIN C12 [get_ports {FIXED_IO_mio[53]}]
set_property PACKAGE_PIN D10 [get_ports {FIXED_IO_mio[52]}]
set_property PACKAGE_PIN C10 [get_ports {FIXED_IO_mio[51]}]
set_property PACKAGE_PIN D13 [get_ports {FIXED_IO_mio[50]}]
set_property PACKAGE_PIN C14 [get_ports {FIXED_IO_mio[49]}]
set_property PACKAGE_PIN D11 [get_ports {FIXED_IO_mio[48]}]
set_property PACKAGE_PIN B10 [get_ports {FIXED_IO_mio[47]}]
set_property PACKAGE_PIN D12 [get_ports {FIXED_IO_mio[46]}]
set_property PACKAGE_PIN B9 [get_ports {FIXED_IO_mio[45]}]
set_property PACKAGE_PIN E13 [get_ports {FIXED_IO_mio[44]}]
set_property PACKAGE_PIN B11 [get_ports {FIXED_IO_mio[43]}]
set_property PACKAGE_PIN D8 [get_ports {FIXED_IO_mio[42]}]
set_property PACKAGE_PIN C8 [get_ports {FIXED_IO_mio[41]}]
set_property PACKAGE_PIN E14 [get_ports {FIXED_IO_mio[40]}]
set_property PACKAGE_PIN C13 [get_ports {FIXED_IO_mio[39]}]
set_property PACKAGE_PIN F13 [get_ports {FIXED_IO_mio[38]}]
set_property PACKAGE_PIN B14 [get_ports {FIXED_IO_mio[37]}]
set_property PACKAGE_PIN A9 [get_ports {FIXED_IO_mio[36]}]
set_property PACKAGE_PIN F14 [get_ports {FIXED_IO_mio[35]}]
set_property PACKAGE_PIN B12 [get_ports {FIXED_IO_mio[34]}]
set_property PACKAGE_PIN G13 [get_ports {FIXED_IO_mio[33]}]
set_property PACKAGE_PIN C7 [get_ports {FIXED_IO_mio[32]}]
set_property PACKAGE_PIN F9 [get_ports {FIXED_IO_mio[31]}]
set_property PACKAGE_PIN A11 [get_ports {FIXED_IO_mio[30]}]
set_property PACKAGE_PIN E8 [get_ports {FIXED_IO_mio[29]}]
set_property PACKAGE_PIN A12 [get_ports {FIXED_IO_mio[28]}]
set_property PACKAGE_PIN D7 [get_ports {FIXED_IO_mio[27]}]
set_property PACKAGE_PIN A13 [get_ports {FIXED_IO_mio[26]}]
set_property PACKAGE_PIN F12 [get_ports {FIXED_IO_mio[25]}]
set_property PACKAGE_PIN B7 [get_ports {FIXED_IO_mio[24]}]
set_property PACKAGE_PIN E11 [get_ports {FIXED_IO_mio[23]}]
set_property PACKAGE_PIN A14 [get_ports {FIXED_IO_mio[22]}]
set_property PACKAGE_PIN F11 [get_ports {FIXED_IO_mio[21]}]
set_property PACKAGE_PIN A8 [get_ports {FIXED_IO_mio[20]}]
set_property PACKAGE_PIN E10 [get_ports {FIXED_IO_mio[19]}]
set_property PACKAGE_PIN A7 [get_ports {FIXED_IO_mio[18]}]
set_property PACKAGE_PIN E9 [get_ports {FIXED_IO_mio[17]}]
set_property PACKAGE_PIN D6 [get_ports {FIXED_IO_mio[16]}]
set_property PACKAGE_PIN E6 [get_ports {FIXED_IO_mio[15]}]
set_property PACKAGE_PIN B6 [get_ports {FIXED_IO_mio[14]}]
set_property PACKAGE_PIN A6 [get_ports {FIXED_IO_mio[13]}]
set_property PACKAGE_PIN C5 [get_ports {FIXED_IO_mio[12]}]
set_property PACKAGE_PIN B4 [get_ports {FIXED_IO_mio[11]}]
set_property PACKAGE_PIN G7 [get_ports {FIXED_IO_mio[10]}]
set_property PACKAGE_PIN C4 [get_ports {FIXED_IO_mio[9]}]
set_property PACKAGE_PIN E5 [get_ports {FIXED_IO_mio[8]}]
set_property PACKAGE_PIN D5 [get_ports {FIXED_IO_mio[7]}]
set_property PACKAGE_PIN A4 [get_ports {FIXED_IO_mio[6]}]
set_property PACKAGE_PIN A3 [get_ports {FIXED_IO_mio[5]}]
set_property PACKAGE_PIN E4 [get_ports {FIXED_IO_mio[4]}]
set_property PACKAGE_PIN F6 [get_ports {FIXED_IO_mio[3]}]
set_property PACKAGE_PIN A2 [get_ports {FIXED_IO_mio[2]}]
set_property PACKAGE_PIN A1 [get_ports {FIXED_IO_mio[1]}]
set_property PACKAGE_PIN G6 [get_ports {FIXED_IO_mio[0]}]
set_property PACKAGE_PIN F3 [get_ports DDR_reset_n]
set_property PACKAGE_PIN V2 [get_ports {DDR_dqs_p[3]}]
set_property PACKAGE_PIN R4 [get_ports DDR_we_n]
set_property PACKAGE_PIN M7 [get_ports FIXED_IO_ddr_vrn]
set_property PACKAGE_PIN N7 [get_ports FIXED_IO_ddr_vrp]
set_property PACKAGE_PIN M4 [get_ports {DDR_addr[0]}]
set_property PACKAGE_PIN M5 [get_ports {DDR_addr[1]}]
set_property PACKAGE_PIN K4 [get_ports {DDR_addr[2]}]
set_property PACKAGE_PIN L4 [get_ports {DDR_addr[3]}]
set_property PACKAGE_PIN K6 [get_ports {DDR_addr[4]}]
set_property PACKAGE_PIN K5 [get_ports {DDR_addr[5]}]
set_property PACKAGE_PIN J7 [get_ports {DDR_addr[6]}]
set_property PACKAGE_PIN J6 [get_ports {DDR_addr[7]}]
set_property PACKAGE_PIN J5 [get_ports {DDR_addr[8]}]
set_property PACKAGE_PIN H5 [get_ports {DDR_addr[9]}]
set_property PACKAGE_PIN J3 [get_ports {DDR_addr[10]}]
set_property PACKAGE_PIN G5 [get_ports {DDR_addr[11]}]
set_property PACKAGE_PIN H4 [get_ports {DDR_addr[12]}]
set_property PACKAGE_PIN G4 [get_ports {DDR_addr[14]}]
set_property PACKAGE_PIN F4 [get_ports {DDR_addr[13]}]
set_property PACKAGE_PIN L7 [get_ports {DDR_ba[0]}]
set_property PACKAGE_PIN L6 [get_ports {DDR_ba[1]}]
set_property PACKAGE_PIN M6 [get_ports {DDR_ba[2]}]
set_property PACKAGE_PIN P3 [get_ports DDR_cas_n]
set_property PACKAGE_PIN V3 [get_ports DDR_cke]
set_property PACKAGE_PIN N5 [get_ports DDR_ck_n]
set_property PACKAGE_PIN N4 [get_ports DDR_ck_p]
set_property PACKAGE_PIN F7 [get_ports FIXED_IO_ps_clk]
set_property PACKAGE_PIN P6 [get_ports DDR_cs_n]
set_property PACKAGE_PIN B1 [get_ports {DDR_dm[0]}]
set_property PACKAGE_PIN H3 [get_ports {DDR_dm[1]}]
set_property PACKAGE_PIN P1 [get_ports {DDR_dm[2]}]
set_property PACKAGE_PIN AA2 [get_ports {DDR_dm[3]}]
set_property PACKAGE_PIN D1 [get_ports {DDR_dq[0]}]
set_property PACKAGE_PIN C3 [get_ports {DDR_dq[1]}]
set_property PACKAGE_PIN B2 [get_ports {DDR_dq[2]}]
set_property PACKAGE_PIN D3 [get_ports {DDR_dq[3]}]
set_property PACKAGE_PIN E3 [get_ports {DDR_dq[4]}]
set_property PACKAGE_PIN E1 [get_ports {DDR_dq[5]}]
set_property PACKAGE_PIN F2 [get_ports {DDR_dq[6]}]
set_property PACKAGE_PIN F1 [get_ports {DDR_dq[7]}]
set_property PACKAGE_PIN G2 [get_ports {DDR_dq[8]}]
set_property PACKAGE_PIN G1 [get_ports {DDR_dq[9]}]
set_property PACKAGE_PIN L1 [get_ports {DDR_dq[10]}]
set_property PACKAGE_PIN L2 [get_ports {DDR_dq[11]}]
set_property PACKAGE_PIN L3 [get_ports {DDR_dq[12]}]
set_property PACKAGE_PIN K1 [get_ports {DDR_dq[13]}]
set_property PACKAGE_PIN J1 [get_ports {DDR_dq[14]}]
set_property PACKAGE_PIN K3 [get_ports {DDR_dq[15]}]
set_property PACKAGE_PIN M1 [get_ports {DDR_dq[16]}]
set_property PACKAGE_PIN T3 [get_ports {DDR_dq[17]}]
set_property PACKAGE_PIN N3 [get_ports {DDR_dq[18]}]
set_property PACKAGE_PIN T1 [get_ports {DDR_dq[19]}]
set_property PACKAGE_PIN R3 [get_ports {DDR_dq[20]}]
set_property PACKAGE_PIN T2 [get_ports {DDR_dq[21]}]
set_property PACKAGE_PIN M2 [get_ports {DDR_dq[22]}]
set_property PACKAGE_PIN R1 [get_ports {DDR_dq[23]}]
set_property PACKAGE_PIN AA3 [get_ports {DDR_dq[24]}]
set_property PACKAGE_PIN U1 [get_ports {DDR_dq[25]}]
set_property PACKAGE_PIN AA1 [get_ports {DDR_dq[26]}]
set_property PACKAGE_PIN U2 [get_ports {DDR_dq[27]}]
set_property PACKAGE_PIN W1 [get_ports {DDR_dq[28]}]
set_property PACKAGE_PIN Y3 [get_ports {DDR_dq[29]}]
set_property PACKAGE_PIN W3 [get_ports {DDR_dq[30]}]
set_property PACKAGE_PIN Y1 [get_ports {DDR_dq[31]}]
set_property PACKAGE_PIN D2 [get_ports {DDR_dqs_n[0]}]
set_property PACKAGE_PIN J2 [get_ports {DDR_dqs_n[1]}]
set_property PACKAGE_PIN P2 [get_ports {DDR_dqs_n[2]}]
set_property PACKAGE_PIN W2 [get_ports {DDR_dqs_n[3]}]
set_property PACKAGE_PIN C2 [get_ports {DDR_dqs_p[0]}]
set_property PACKAGE_PIN H2 [get_ports {DDR_dqs_p[1]}]
set_property PACKAGE_PIN N2 [get_ports {DDR_dqs_p[2]}]
set_property SLEW FAST [get_ports FIXED_IO_ps_clk]



####################################################################################
# Constraints from file : 'ps_system_axi_gpio_0_0_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------

set_property BOARD_PART_PIN leds_8bits_tri_o_0 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN T22 [get_ports {led[0]}]

set_property BOARD_PART_PIN leds_8bits_tri_o_1 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN T21 [get_ports {led[1]}]

set_property BOARD_PART_PIN leds_8bits_tri_o_2 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN U22 [get_ports {led[2]}]

set_property BOARD_PART_PIN leds_8bits_tri_o_3 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN U21 [get_ports {led[3]}]

set_property BOARD_PART_PIN leds_8bits_tri_o_4 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN V22 [get_ports {led[4]}]

set_property BOARD_PART_PIN leds_8bits_tri_o_5 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN W22 [get_ports {led[5]}]

set_property BOARD_PART_PIN leds_8bits_tri_o_6 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN U19 [get_ports {led[6]}]

set_property BOARD_PART_PIN leds_8bits_tri_o_7 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN U14 [get_ports {led[7]}]

set_property BOARD_PART_PIN sws_8bits_tri_i_0 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[0]}]
set_property PACKAGE_PIN F22 [get_ports {sw[0]}]

set_property BOARD_PART_PIN sws_8bits_tri_i_1 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[1]}]
set_property PACKAGE_PIN G22 [get_ports {sw[1]}]

set_property BOARD_PART_PIN sws_8bits_tri_i_2 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[2]}]
set_property PACKAGE_PIN H22 [get_ports {sw[2]}]

set_property BOARD_PART_PIN sws_8bits_tri_i_3 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[3]}]
set_property PACKAGE_PIN F21 [get_ports {sw[3]}]

set_property BOARD_PART_PIN sws_8bits_tri_i_4 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[4]}]
set_property PACKAGE_PIN H19 [get_ports {sw[4]}]

set_property BOARD_PART_PIN sws_8bits_tri_i_5 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[5]}]
set_property PACKAGE_PIN H18 [get_ports {sw[5]}]

set_property BOARD_PART_PIN sws_8bits_tri_i_6 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[6]}]
set_property PACKAGE_PIN H17 [get_ports {sw[6]}]

set_property BOARD_PART_PIN sws_8bits_tri_i_7 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[7]}]
set_property PACKAGE_PIN M15 [get_ports {sw[7]}]



####################################################################################
# Constraints from file : 'ps_system_axi_gpio_0_0.xdc'
####################################################################################

# (c) Copyright 2009 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.

current_instance proc_system_0/ps_system_i/axi_gpio_0/U0
set_false_path -to [get_pins -hier *cdc_to*/D]



####################################################################################
# Constraints from file : 'ps_system_axi_gpio_1_0_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------

current_instance -quiet
set_property BOARD_PART_PIN btns_5bits_tri_i_0 [get_ports {btn[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {btn[0]}]
set_property PACKAGE_PIN P16 [get_ports {btn[0]}]

set_property BOARD_PART_PIN btns_5bits_tri_i_1 [get_ports {btn[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {btn[1]}]
set_property PACKAGE_PIN R16 [get_ports {btn[1]}]

set_property BOARD_PART_PIN btns_5bits_tri_i_2 [get_ports {btn[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {btn[2]}]
set_property PACKAGE_PIN N15 [get_ports {btn[2]}]

set_property BOARD_PART_PIN btns_5bits_tri_i_3 [get_ports {btn[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {btn[3]}]
set_property PACKAGE_PIN R18 [get_ports {btn[3]}]

set_property BOARD_PART_PIN btns_5bits_tri_i_4 [get_ports {btn[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {btn[4]}]
set_property PACKAGE_PIN T18 [get_ports {btn[4]}]



####################################################################################
# Constraints from file : 'ps_system_axi_gpio_1_0.xdc'
####################################################################################

# (c) Copyright 2009 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.

current_instance proc_system_0/ps_system_i/axi_gpio_1/U0
set_false_path -to [get_pins -hier *cdc_to*/D]



####################################################################################
# Constraints from file : 'ps_system_rst_ps7_0_100M_0_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------



####################################################################################
# Constraints from file : 'ps_system_rst_ps7_0_100M_0.xdc'
####################################################################################


# file: ps_system_rst_ps7_0_100M_0.xdc
# (c) Copyright 2009 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.

current_instance -quiet
current_instance proc_system_0/ps_system_i/rst_ps7_0_100M/U0
set_false_path -to [get_pins -hier *cdc_to*/D]


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
