# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/ip/bd_processor_rst_ps7_0_100M_0/bd_processor_rst_ps7_0_100M_0.xci
# IP: The module: 'bd_processor_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/ip/bd_processor_rst_ps7_0_100M_0/bd_processor_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_processor_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/ip/bd_processor_rst_ps7_0_100M_0/bd_processor_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_processor_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/ip/bd_processor_rst_ps7_0_100M_0/bd_processor_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_processor_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/ip/bd_processor_rst_ps7_0_100M_0/bd_processor_rst_ps7_0_100M_0.xci
# IP: The module: 'bd_processor_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/ip/bd_processor_rst_ps7_0_100M_0/bd_processor_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_processor_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/ip/bd_processor_rst_ps7_0_100M_0/bd_processor_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_processor_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/ip/bd_processor_rst_ps7_0_100M_0/bd_processor_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_processor_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
