# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/constr/top_pins.xdc

# XDC: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/constr/timing.xdc

# Block Designs: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/bd_processor.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_processor || ORIG_REF_NAME==bd_processor} -quiet] -quiet

# IP: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/ip/bd_processor_processing_system7_0_0/bd_processor_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_processor_processing_system7_0_0 || ORIG_REF_NAME==bd_processor_processing_system7_0_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/ip/bd_processor_xadc_wiz_0_0/bd_processor_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_processor_xadc_wiz_0_0 || ORIG_REF_NAME==bd_processor_xadc_wiz_0_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/ip/bd_processor_axi_gpio_0_0/bd_processor_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_processor_axi_gpio_0_0 || ORIG_REF_NAME==bd_processor_axi_gpio_0_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/ip/bd_processor_xbar_0/bd_processor_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_processor_xbar_0 || ORIG_REF_NAME==bd_processor_xbar_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/ip/bd_processor_auto_pc_0/bd_processor_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_processor_auto_pc_0 || ORIG_REF_NAME==bd_processor_auto_pc_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/ip/bd_processor_ps7_0_axi_periph_0/bd_processor_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_processor_ps7_0_axi_periph_0 || ORIG_REF_NAME==bd_processor_ps7_0_axi_periph_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/ip/bd_processor_rst_ps7_0_100M_0/bd_processor_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_processor_rst_ps7_0_100M_0 || ORIG_REF_NAME==bd_processor_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: /home/petr/Projects/fpga_edu/zedboard/wrk/communicator_tcp_ip/rtl/src/ip/bd_processor/bd_processor_ooc.xdc
