# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/petr/Projects/fpga_edu/zedboard/wrk/ps_freertos_systems/rtl/src/constr/timing.xdc

# XDC: /home/petr/Projects/fpga_edu/zedboard/wrk/ps_freertos_systems/rtl/src/constr/top_pins.xdc

# Block Designs: /home/petr/Projects/fpga_edu/zedboard/wrk/ps_freertos_systems/rtl/src/ip/p_system/p_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p_system || ORIG_REF_NAME==p_system} -quiet] -quiet

# IP: /home/petr/Projects/fpga_edu/zedboard/wrk/ps_freertos_systems/rtl/src/ip/p_system/ip/p_system_processing_system7_0_0/p_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p_system_processing_system7_0_0 || ORIG_REF_NAME==p_system_processing_system7_0_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga_edu/zedboard/wrk/ps_freertos_systems/rtl/src/ip/p_system/ip/p_system_axi_gpio_0_0/p_system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p_system_axi_gpio_0_0 || ORIG_REF_NAME==p_system_axi_gpio_0_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga_edu/zedboard/wrk/ps_freertos_systems/rtl/src/ip/p_system/ip/p_system_axi_gpio_1_0/p_system_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p_system_axi_gpio_1_0 || ORIG_REF_NAME==p_system_axi_gpio_1_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga_edu/zedboard/wrk/ps_freertos_systems/rtl/src/ip/p_system/ip/p_system_xbar_0/p_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p_system_xbar_0 || ORIG_REF_NAME==p_system_xbar_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga_edu/zedboard/wrk/ps_freertos_systems/rtl/src/ip/p_system/ip/p_system_auto_pc_0/p_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p_system_auto_pc_0 || ORIG_REF_NAME==p_system_auto_pc_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga_edu/zedboard/wrk/ps_freertos_systems/rtl/src/ip/p_system/ip/p_system_ps7_0_axi_periph_0/p_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==p_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga_edu/zedboard/wrk/ps_freertos_systems/rtl/src/ip/p_system/ip/p_system_rst_ps7_0_100M_0/p_system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==p_system_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: /home/petr/Projects/fpga_edu/zedboard/wrk/ps_freertos_systems/rtl/src/ip/p_system/p_system_ooc.xdc
