# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/petr/Projects/zedboard/wrk/axitest/src/ip/jtag_axi_0/jtag_axi_0.xci
# IP: The module: 'jtag_axi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/petr/Projects/zedboard/wrk/axitest/src/ip/jtag_axi_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/petr/Projects/zedboard/wrk/axitest/src/ip/jtag_axi_0/jtag_axi_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/petr/Projects/zedboard/wrk/axitest/src/ip/jtag_axi_0/jtag_axi_0.xci
# IP: The module: 'jtag_axi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/petr/Projects/zedboard/wrk/axitest/src/ip/jtag_axi_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/petr/Projects/zedboard/wrk/axitest/src/ip/jtag_axi_0/jtag_axi_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
