# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ip/ps_system_rst_ps7_0_100M_0/ps_system_rst_ps7_0_100M_0.xci
# IP: The module: 'ps_system_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ip/ps_system_rst_ps7_0_100M_0/ps_system_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ip/ps_system_rst_ps7_0_100M_0/ps_system_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ip/ps_system_rst_ps7_0_100M_0/ps_system_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ip/ps_system_rst_ps7_0_100M_0/ps_system_rst_ps7_0_100M_0.xci
# IP: The module: 'ps_system_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ip/ps_system_rst_ps7_0_100M_0/ps_system_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ip/ps_system_rst_ps7_0_100M_0/ps_system_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ip/ps_system_rst_ps7_0_100M_0/ps_system_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
