# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k160tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/vivado/adc_to_udp_ip.cache/wt [current_project]
set_property parent.project_path /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/vivado/adc_to_udp_ip.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/vivado/adc_to_udp_ip.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/hdl/utils/rst_pospone.vhd
  /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/hdl/usr_udp_ip_to_temac.vhd
  /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/hdl/adc/one_bit_assert.vhd
  /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/hdl/vga/vga.vhd
  /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/hdl/adc_to_udp_ip.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/hdl/adc/adc.vhd
read_ip -quiet /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/adc_axis_fifo/adc_axis_fifo.xci
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/adc_axis_fifo/adc_axis_fifo_ooc.xdc]

read_ip -quiet /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0_ooc.xdc]

read_ip -quiet /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/gig_ethernet_pcs_pma_1/gig_ethernet_pcs_pma_1.xci
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/gig_ethernet_pcs_pma_1/gig_ethernet_pcs_pma_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/gig_ethernet_pcs_pma_1/synth/gig_ethernet_pcs_pma_1.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/gig_ethernet_pcs_pma_1/synth/gig_ethernet_pcs_pma_1_ooc.xdc]

read_ip -quiet /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/vivado/adc_to_udp_ip.srcs/sources_1/ip/ila_signal_tester/ila_signal_tester.xci
set_property used_in_synthesis false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/vivado/adc_to_udp_ip.srcs/sources_1/ip/ila_signal_tester/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/vivado/adc_to_udp_ip.srcs/sources_1/ip/ila_signal_tester/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/vivado/adc_to_udp_ip.srcs/sources_1/ip/ila_signal_tester/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/vivado/adc_to_udp_ip.srcs/sources_1/ip/ila_signal_tester/ila_signal_tester_ooc.xdc]

read_ip -quiet /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/vivado/adc_to_udp_ip.srcs/sources_1/ip/selectio_wiz_4ch_and_fco/selectio_wiz_4ch_and_fco.xci
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/vivado/adc_to_udp_ip.srcs/sources_1/ip/selectio_wiz_4ch_and_fco/selectio_wiz_4ch_and_fco_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/vivado/adc_to_udp_ip.srcs/sources_1/ip/selectio_wiz_4ch_and_fco/selectio_wiz_4ch_and_fco.xdc]

read_ip -quiet /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/tri_mode_ethernet_mac_0/tri_mode_ethernet_mac_0.xci
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_clocks.xdc]

read_ip -quiet /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/vio_0/vio_0/vio_0.xci
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/vio_0/vio_0/vio_0.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/vio_0/vio_0/vio_0_ooc.xdc]

read_ip -quiet /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/vio_1/vio_1/vio_1.xci
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/vio_1/vio_1/vio_1.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/ip/vio_1/vio_1/vio_1_ooc.xdc]

read_ip -quiet /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/vivado/adc_to_udp_ip.srcs/sources_1/ip/vio_2/vio_2.xci
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/vivado/adc_to_udp_ip.srcs/sources_1/ip/vio_2/vio_2.xdc]
set_property used_in_implementation false [get_files -all /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/vivado/adc_to_udp_ip.srcs/sources_1/ip/vio_2/vio_2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/constr_n/clocks.xdc
set_property used_in_implementation false [get_files /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/constr_n/clocks.xdc]

read_xdc /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/constr_n/adc_pins.xdc
set_property used_in_implementation false [get_files /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/constr_n/adc_pins.xdc]

read_xdc /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/constr_n/others_pins.xdc
set_property used_in_implementation false [get_files /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/constr_n/others_pins.xdc]

read_xdc /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/constr_n/sfp_pins.xdc
set_property used_in_implementation false [get_files /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/constr_n/sfp_pins.xdc]

read_xdc /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/constr_n/adc_timing.xdc
set_property used_in_implementation false [get_files /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/constr_n/adc_timing.xdc]

read_xdc /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/constr_n/debug.xdc
set_property used_in_implementation false [get_files /home/petr/Projects/CVUT/adc2udp_stream_ver3_183/src/constr_n/debug.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top adc_to_udp_ip -part xc7k160tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef adc_to_udp_ip.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file adc_to_udp_ip_utilization_synth.rpt -pb adc_to_udp_ip_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
