# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ps_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_system || ORIG_REF_NAME==ps_system} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ip/ps_system_processing_system7_0_0/ps_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_system_processing_system7_0_0 || ORIG_REF_NAME==ps_system_processing_system7_0_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ip/ps_system_axi_gpio_0_0/ps_system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_system_axi_gpio_0_0 || ORIG_REF_NAME==ps_system_axi_gpio_0_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ip/ps_system_axi_gpio_1_0/ps_system_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_system_axi_gpio_1_0 || ORIG_REF_NAME==ps_system_axi_gpio_1_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ip/ps_system_xbar_0/ps_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_system_xbar_0 || ORIG_REF_NAME==ps_system_xbar_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ip/ps_system_ps7_0_axi_periph_0/ps_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==ps_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ip/ps_system_rst_ps7_0_100M_0/ps_system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==ps_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ip/ps_system_auto_pc_0/ps_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_system_auto_pc_0 || ORIG_REF_NAME==ps_system_auto_pc_0} -quiet] -quiet

# XDC: /home/petr/Projects/fpga/zedboard/wrk/ps_freertos_lwip/rtl/src/ip/ps_system/ps_system_ooc.xdc
